# Generated by scripts/generate_contracts.py. Do not edit.
from __future__ import annotations

from decimal import Decimal
from typing import Final, Literal, TypeGuard, cast

_RAW_SPECS = {
    "AUDUSD": {
        "base_currency": "AUD",
        "broad_max_price": "2.0",
        "broad_min_price": "0.2",
        "display_decimal_max": 6,
        "display_decimal_min": 4,
        "extreme_jump_pips": "20",
        "extreme_spread_pips": "5",
        "pip_size": "0.0001",
        "quote_currency": "USD",
    },
    "EURUSD": {
        "base_currency": "EUR",
        "broad_max_price": "2.5",
        "broad_min_price": "0.5",
        "display_decimal_max": 6,
        "display_decimal_min": 4,
        "extreme_jump_pips": "20",
        "extreme_spread_pips": "5",
        "pip_size": "0.0001",
        "quote_currency": "USD",
    },
    "GBPUSD": {
        "base_currency": "GBP",
        "broad_max_price": "3.5",
        "broad_min_price": "0.5",
        "display_decimal_max": 6,
        "display_decimal_min": 4,
        "extreme_jump_pips": "20",
        "extreme_spread_pips": "5",
        "pip_size": "0.0001",
        "quote_currency": "USD",
    },
    "USDJPY": {
        "base_currency": "USD",
        "broad_max_price": "250",
        "broad_min_price": "50",
        "display_decimal_max": 4,
        "display_decimal_min": 2,
        "extreme_jump_pips": "20",
        "extreme_spread_pips": "5",
        "pip_size": "0.01",
        "quote_currency": "JPY",
    },
}

type SupportedInstrument = Literal["EURUSD", "GBPUSD", "USDJPY", "AUDUSD"]
SUPPORTED_INSTRUMENTS: Final = ("EURUSD", "GBPUSD", "USDJPY", "AUDUSD")
INSTRUMENT_SPECS: Final = {
    symbol: {
        **values,
        "pip_size": Decimal(str(values["pip_size"])),
        "broad_min_price": Decimal(str(values["broad_min_price"])),
        "broad_max_price": Decimal(str(values["broad_max_price"])),
        "extreme_spread_pips": Decimal(str(values["extreme_spread_pips"])),
        "extreme_jump_pips": Decimal(str(values["extreme_jump_pips"])),
    }
    for symbol, values in _RAW_SPECS.items()
}


def is_supported_instrument(value: object) -> TypeGuard[SupportedInstrument]:
    return isinstance(value, str) and value in INSTRUMENT_SPECS


def instrument_spec(symbol: str) -> dict[str, object]:
    if symbol not in INSTRUMENT_SPECS:
        raise ValueError(f"unsupported instrument: {symbol}")
    return cast(dict[str, object], INSTRUMENT_SPECS[symbol])
