from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRY = ROOT / "packages/contracts/instrument_specs.json"
PYTHON_OUTPUT = ROOT / "packages/contracts/src/forex_contracts/instruments_generated.py"
TYPESCRIPT_OUTPUT = ROOT / "apps/browser_bridge/src/instruments.generated.ts"
PRICE_TICK_SCHEMA_OUTPUT = ROOT / "docs/contracts/PRICE_TICK_v0.2.schema.json"
RAW_EVENT_SCHEMA_OUTPUT = ROOT / "docs/contracts/RAW_PROVIDER_EVENT_v0.1.schema.json"


def render_python(specs: dict[str, dict[str, object]]) -> str:
    payload = json.dumps(specs, indent=4, sort_keys=True)
    source = (
        "# Generated by scripts/generate_contracts.py. Do not edit.\n"
        "from __future__ import annotations\n\n"
        "from decimal import Decimal\n"
        "from typing import Final, Literal, TypeGuard, cast\n\n"
        f"_RAW_SPECS = {payload}\n\n"
        "type SupportedInstrument = Literal[" + ", ".join(repr(symbol) for symbol in specs) + "]\n"
        f"SUPPORTED_INSTRUMENTS: Final = {tuple(specs)}\n"
        "INSTRUMENT_SPECS: Final = {\n"
        "    symbol: {\n"
        "        **values,\n"
        '        "pip_size": Decimal(str(values["pip_size"])),\n'
        '        "broad_min_price": Decimal(str(values["broad_min_price"])),\n'
        '        "broad_max_price": Decimal(str(values["broad_max_price"])),\n'
        '        "extreme_spread_pips": Decimal(str(values["extreme_spread_pips"])),\n'
        '        "extreme_jump_pips": Decimal(str(values["extreme_jump_pips"])),\n'
        "    }\n"
        "    for symbol, values in _RAW_SPECS.items()\n"
        "}\n\n"
        "def is_supported_instrument(value: object) -> TypeGuard[SupportedInstrument]:\n"
        "    return isinstance(value, str) and value in INSTRUMENT_SPECS\n\n"
        "def instrument_spec(symbol: str) -> dict[str, object]:\n"
        "    if symbol not in INSTRUMENT_SPECS:\n"
        '        raise ValueError(f"unsupported instrument: {symbol}")\n'
        "    return cast(dict[str, object], INSTRUMENT_SPECS[symbol])\n"
    )
    ruff = shutil.which("ruff")
    if ruff is None:
        raise RuntimeError("ruff is required to generate deterministic Python artifacts")
    formatted = subprocess.run(  # noqa: S603 - resolved trusted development executable
        [ruff, "format", "--stdin-filename", str(PYTHON_OUTPUT), "-"],
        input=source,
        text=True,
        capture_output=True,
        check=True,
    )
    return formatted.stdout


def render_typescript(specs: dict[str, dict[str, object]]) -> str:
    payload = json.dumps(specs, indent=2)
    return (
        "// Generated by scripts/generate_contracts.py. Do not edit.\n"
        f"export const INSTRUMENT_SPECS = {payload} as const;\n\n"
        "export type SupportedInstrument = keyof typeof INSTRUMENT_SPECS;\n"
        "export const SUPPORTED_INSTRUMENTS = Object.freeze(\n"
        "  Object.keys(INSTRUMENT_SPECS) as SupportedInstrument[],\n"
        ");\n\n"
        "export function isSupportedInstrument(value: unknown): value is SupportedInstrument {\n"
        '  return typeof value === "string" && value in INSTRUMENT_SPECS;\n'
        "}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    specs = json.loads(REGISTRY.read_text())
    from forex_contracts import PriceTickV02, RawProviderEvent

    outputs = {
        PYTHON_OUTPUT: render_python(specs),
        TYPESCRIPT_OUTPUT: render_typescript(specs),
        PRICE_TICK_SCHEMA_OUTPUT: (
            json.dumps(PriceTickV02.model_json_schema(), indent=2, sort_keys=True) + "\n"
        ),
        RAW_EVENT_SCHEMA_OUTPUT: (
            json.dumps(RawProviderEvent.model_json_schema(), indent=2, sort_keys=True) + "\n"
        ),
    }
    stale = [
        path
        for path, content in outputs.items()
        if not path.exists() or path.read_text() != content
    ]
    if args.check:
        if stale:
            print(
                "stale generated files:", ", ".join(str(path.relative_to(ROOT)) for path in stale)
            )
            return 1
        print("generated contract artifacts are current")
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    print("generated:", ", ".join(str(path.relative_to(ROOT)) for path in outputs))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
